# Generated by Django 4.2.3 on 2023-08-01 21:04

import Main.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NameFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "file",
                    models.FileField(null=True, upload_to=Main.models.upload_to_docs),
                ),
            ],
        ),
    ]
