# Generated by Django 4.2.4 on 2023-08-22 10:41

import Main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField()),
                ('excel_sheet', models.FileField(null=True, upload_to=Main.models.upload_to_excel)),
            ],
        ),
    ]
